import { MigrationInterface, QueryRunner } from "typeorm";

export class Latest1767548406847 implements MigrationInterface {
    name = 'Latest1767548406847'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP FOREIGN KEY \`FK_2f1a2d477de650a8abb9af37d52\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP FOREIGN KEY \`FK_8679e2ff150ff0e253189ca0253\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_c8f626e1e943aabb0f90fb8ee61\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_f9238c3e3739dc40322f577fc46\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP FOREIGN KEY \`FK_2fc2b11c69ee4d0cee9eed51e09\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP FOREIGN KEY \`FK_4ce325bde523ed1e9aead042ea5\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP FOREIGN KEY \`FK_be8d9d517a91f237ba098909c16\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP FOREIGN KEY \`FK_bfceb70ea48147615ecb633f646\``);
        await queryRunner.query(`DROP INDEX \`FK_ee611bcc77ea9cbb2a3d747d22b\` ON \`class_bookings\``);
        await queryRunner.query(`DROP INDEX \`IDX_2f1a2d477de650a8abb9af37d5\` ON \`support_tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_8679e2ff150ff0e253189ca025\` ON \`support_tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba7b1a2ed4051fb3b39ff95444\` ON \`support_tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_cae81694804986ef32be155d34\` ON \`support_tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_046fd8785af0703d082856a41b\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_bed20e82fea1ff3cabe4b526df\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8f626e1e943aabb0f90fb8ee6\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_f9238c3e3739dc40322f577fc4\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_90c78d3c32a3346772edf34e73\` ON \`refunds\``);
        await queryRunner.query(`DROP INDEX \`IDX_be8d9d517a91f237ba098909c1\` ON \`refunds\``);
        await queryRunner.query(`DROP INDEX \`IDX_3f32ee6d2385d9a8bc0cc92af5\` ON \`payouts\``);
        await queryRunner.query(`DROP INDEX \`IDX_bfceb70ea48147615ecb633f64\` ON \`payouts\``);
        await queryRunner.query(`CREATE TABLE \`assignment_submissions\` (\`id\` varchar(36) NOT NULL, \`assignmentId\` varchar(255) NOT NULL, \`studentId\` varchar(255) NOT NULL, \`files\` json NULL, \`submissionText\` text NULL, \`submittedAt\` timestamp NULL, \`isLate\` tinyint NOT NULL DEFAULT 0, \`status\` enum ('pending', 'submitted', 'graded', 'returned') NOT NULL DEFAULT 'pending', \`score\` decimal(10,2) NULL, \`maxScore\` decimal(10,2) NULL, \`feedback\` text NULL, \`gradedAt\` timestamp NULL, \`gradedBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`isDeleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`assignments\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`classId\` varchar(255) NULL, \`teacherBookingId\` varchar(255) NULL, \`teacherId\` varchar(255) NOT NULL, \`type\` enum ('homework', 'project', 'quiz', 'exam') NOT NULL DEFAULT 'homework', \`maxScore\` decimal(10,2) NOT NULL DEFAULT '100.00', \`weight\` decimal(5,2) NOT NULL DEFAULT '0.00', \`dueDate\` timestamp NULL, \`submissionDate\` timestamp NULL, \`allowLateSubmission\` tinyint NOT NULL DEFAULT 0, \`latePenalty\` decimal(5,2) NOT NULL DEFAULT '0.00', \`instructions\` text NULL, \`attachments\` json NULL, \`rubric\` json NULL, \`status\` enum ('draft', 'published', 'in_progress', 'completed', 'graded') NOT NULL DEFAULT 'draft', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`isDeleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`class_bookings\` DROP COLUMN \`classEntityId\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`userId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`assigneeId\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`assigneeId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`reviewerId\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`reviewerId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`revieweeId\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`revieweeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`classBookingId\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`classBookingId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`teacherBookingId\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`teacherBookingId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`userId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP COLUMN \`teacherId\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD \`teacherId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`class_bookings\` ADD CONSTRAINT \`FK_491babcf74095cb08354f70c110\` FOREIGN KEY (\`classId\`) REFERENCES \`classes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD CONSTRAINT \`FK_8679e2ff150ff0e253189ca0253\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD CONSTRAINT \`FK_2f1a2d477de650a8abb9af37d52\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_f9238c3e3739dc40322f577fc46\` FOREIGN KEY (\`reviewerId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_c8f626e1e943aabb0f90fb8ee61\` FOREIGN KEY (\`revieweeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD CONSTRAINT \`FK_2fc2b11c69ee4d0cee9eed51e09\` FOREIGN KEY (\`classBookingId\`) REFERENCES \`class_bookings\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD CONSTRAINT \`FK_4ce325bde523ed1e9aead042ea5\` FOREIGN KEY (\`teacherBookingId\`) REFERENCES \`teacher_bookings\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD CONSTRAINT \`FK_be8d9d517a91f237ba098909c16\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD CONSTRAINT \`FK_bfceb70ea48147615ecb633f646\` FOREIGN KEY (\`teacherId\`) REFERENCES \`teachers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assignment_submissions\` ADD CONSTRAINT \`FK_6e8a68594fde52f61876a40489c\` FOREIGN KEY (\`assignmentId\`) REFERENCES \`assignments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assignment_submissions\` ADD CONSTRAINT \`FK_dfb5017c979e0e8e47659b0da24\` FOREIGN KEY (\`studentId\`) REFERENCES \`students\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assignment_submissions\` ADD CONSTRAINT \`FK_fe1bd3cc577c4cbcaed1fe8e276\` FOREIGN KEY (\`gradedBy\`) REFERENCES \`teachers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assignments\` ADD CONSTRAINT \`FK_c5382064b68e93e2ac371de898e\` FOREIGN KEY (\`classId\`) REFERENCES \`classes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assignments\` ADD CONSTRAINT \`FK_2bc0fcd06bfb7d55b734706ea35\` FOREIGN KEY (\`teacherBookingId\`) REFERENCES \`teacher_bookings\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assignments\` ADD CONSTRAINT \`FK_e9a3111140d313859c9dfa8f22d\` FOREIGN KEY (\`teacherId\`) REFERENCES \`teachers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`assignments\` DROP FOREIGN KEY \`FK_e9a3111140d313859c9dfa8f22d\``);
        await queryRunner.query(`ALTER TABLE \`assignments\` DROP FOREIGN KEY \`FK_2bc0fcd06bfb7d55b734706ea35\``);
        await queryRunner.query(`ALTER TABLE \`assignments\` DROP FOREIGN KEY \`FK_c5382064b68e93e2ac371de898e\``);
        await queryRunner.query(`ALTER TABLE \`assignment_submissions\` DROP FOREIGN KEY \`FK_fe1bd3cc577c4cbcaed1fe8e276\``);
        await queryRunner.query(`ALTER TABLE \`assignment_submissions\` DROP FOREIGN KEY \`FK_dfb5017c979e0e8e47659b0da24\``);
        await queryRunner.query(`ALTER TABLE \`assignment_submissions\` DROP FOREIGN KEY \`FK_6e8a68594fde52f61876a40489c\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP FOREIGN KEY \`FK_bfceb70ea48147615ecb633f646\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP FOREIGN KEY \`FK_be8d9d517a91f237ba098909c16\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP FOREIGN KEY \`FK_4ce325bde523ed1e9aead042ea5\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP FOREIGN KEY \`FK_2fc2b11c69ee4d0cee9eed51e09\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_c8f626e1e943aabb0f90fb8ee61\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_f9238c3e3739dc40322f577fc46\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP FOREIGN KEY \`FK_2f1a2d477de650a8abb9af37d52\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP FOREIGN KEY \`FK_8679e2ff150ff0e253189ca0253\``);
        await queryRunner.query(`ALTER TABLE \`class_bookings\` DROP FOREIGN KEY \`FK_491babcf74095cb08354f70c110\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payouts\` DROP COLUMN \`teacherId\``);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD \`teacherId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`userId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`teacherBookingId\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`teacherBookingId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`refunds\` DROP COLUMN \`classBookingId\``);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD \`classBookingId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`revieweeId\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`revieweeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`reviewerId\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`reviewerId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`assigneeId\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`assigneeId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD \`userId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`class_bookings\` ADD \`classEntityId\` varchar(36) NULL`);
        await queryRunner.query(`DROP TABLE \`assignments\``);
        await queryRunner.query(`DROP TABLE \`assignment_submissions\``);
        await queryRunner.query(`CREATE INDEX \`IDX_bfceb70ea48147615ecb633f64\` ON \`payouts\` (\`teacherId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3f32ee6d2385d9a8bc0cc92af5\` ON \`payouts\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_be8d9d517a91f237ba098909c1\` ON \`refunds\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_90c78d3c32a3346772edf34e73\` ON \`refunds\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f9238c3e3739dc40322f577fc4\` ON \`reviews\` (\`reviewerId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c8f626e1e943aabb0f90fb8ee6\` ON \`reviews\` (\`revieweeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bed20e82fea1ff3cabe4b526df\` ON \`reviews\` (\`reviewerRole\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_046fd8785af0703d082856a41b\` ON \`reviews\` (\`revieweeRole\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_cae81694804986ef32be155d34\` ON \`support_tickets\` (\`priority\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ba7b1a2ed4051fb3b39ff95444\` ON \`support_tickets\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8679e2ff150ff0e253189ca025\` ON \`support_tickets\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_2f1a2d477de650a8abb9af37d5\` ON \`support_tickets\` (\`assigneeId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_ee611bcc77ea9cbb2a3d747d22b\` ON \`class_bookings\` (\`classEntityId\`)`);
        await queryRunner.query(`ALTER TABLE \`payouts\` ADD CONSTRAINT \`FK_bfceb70ea48147615ecb633f646\` FOREIGN KEY (\`teacherId\`) REFERENCES \`teachers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD CONSTRAINT \`FK_be8d9d517a91f237ba098909c16\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD CONSTRAINT \`FK_4ce325bde523ed1e9aead042ea5\` FOREIGN KEY (\`teacherBookingId\`) REFERENCES \`teacher_bookings\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refunds\` ADD CONSTRAINT \`FK_2fc2b11c69ee4d0cee9eed51e09\` FOREIGN KEY (\`classBookingId\`) REFERENCES \`class_bookings\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_f9238c3e3739dc40322f577fc46\` FOREIGN KEY (\`reviewerId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_c8f626e1e943aabb0f90fb8ee61\` FOREIGN KEY (\`revieweeId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD CONSTRAINT \`FK_8679e2ff150ff0e253189ca0253\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD CONSTRAINT \`FK_2f1a2d477de650a8abb9af37d52\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
